In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import scipy.stats as st
import random
import seaborn as sns

In [3]:
#Data is imported and checked the variables

df5_path= pd.read_csv("C:/Users/ouzgr/OneDrive/Masaüstü/data for project/2018.csv") 
df6_path= pd.read_csv("C:/Users/ouzgr/OneDrive/Masaüstü/data for project/2019.csv")
df7_path= pd.read_csv("C:/Users/ouzgr/OneDrive/Masaüstü/data for project/2020.csv")
df8_path= pd.read_csv("C:/Users/ouzgr/OneDrive/Masaüstü/data for project/2021.csv")

#frames = [df5, df6, df7,df8,df9]
#df = pd.concat(frames)

In [4]:
df7_path.columns

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual', 'Year'],
      dtype='object')

In [5]:
df7_path.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153 entries, 0 to 152
Data columns (total 21 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country name                                153 non-null    object
 1   Regional indicator                          153 non-null    object
 2   Ladder score                                153 non-null    float64
 3   Standard error of ladder score              153 non-null    float64
 4   upperwhisker                                153 non-null    float64
 5   lowerwhisker                                153 non-null    float64
 6   Logged GDP per capita                       153 non-null    float64
 7   Social support                              153 non-null    float64
 8   Healthy life expectancy                     153 non-null    float64
 9   Freedom to make life choices                153 non-null    float64
 10  Generosity                                  153 non-null    float64
 11  Perceptions of corruption                   153 non-null    float64
 12  Ladder score in Dystopia                    153 non-null    float64
 13  Explained by: Log GDP per capita            153 non-null    float64
 14  Explained by: Social support                153 non-null    float64
 15  Explained by: Healthy life expectancy       153 non-null    float64
 16  Explained by: Freedom to make life choices  153 non-null    float64
 17  Explained by: Generosity                    153 non-null    float64
 18  Explained by: Perceptions of corruption     153 non-null    float64
 19  Dystopia + residual                         153 non-null    float64
 20  Year                                        153 non-null    int64
dtypes: float64(18), int64(1), object(2)
memory usage: 25.2+ KB

In [6]:
df_2020 = df7_path[["Country name","Logged GDP per capita", "Social support", "Healthy life expectancy",
       "Freedom to make life choices", "Generosity","Ladder score",
       "Perceptions of corruption","Year"]]

In [7]:
df_2020.head()

,Country name,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Ladder score,Perceptions of corruption,Year
0,Finland,10.639267,0.954330,71.900825,0.949172,-0.059482,7.8087,0.195445,2020
1,Denmark,10.774001,0.955991,72.402504,0.951444,0.066202,7.6456,0.168489,2020
2,Switzerland,10.979933,0.942847,74.102448,0.921337,0.105911,7.5599,0.303728,2020
3,Iceland,10.772559,0.974670,73.000000,0.948892,0.246944,7.5045,0.711710,2020
4,Norway,11.087804,0.952487,73.200783,0.955750,0.134533,7.4880,0.263218,2020

In [8]:
df5_path.columns

Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Year'],
      dtype='object')

In [9]:
df_2018 = df5_path[['Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption','Year']]

In [10]:
df6_path.columns

Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Year'],
      dtype='object')

In [11]:
df_2019 = df6_path[['Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption','Year']]

In [12]:
df8_path.columns

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual', 'Year'],
      dtype='object')

In [13]:
df_2021 = df8_path[['Country name', 'Ladder score', 'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption','Year']]

In [14]:
#As we have long column names, i will change some of them 
df_2021_renamed= df_2021.rename(columns = {'Country name':'Country or region' ,'Ladder score':'Score', 'Logged GDP per capita':'GDP per capita'})
df_2021_renamed.head()

,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Year
0,Finland,7.842,10.775,0.954,72.0,0.949,-0.098,0.186,2021
1,Denmark,7.620,10.933,0.954,72.7,0.946,0.030,0.179,2021
2,Switzerland,7.571,11.117,0.942,74.4,0.919,0.025,0.292,2021
3,Iceland,7.554,10.878,0.983,73.0,0.955,0.160,0.673,2021
4,Netherlands,7.464,10.932,0.942,72.4,0.913,0.175,0.338,2021

In [15]:
df_2020_renamed= df_2020.rename(columns = {'Country name':'Country or region' ,'Ladder score':'Score', 'Logged GDP per capita':'GDP per capita'})
df_2020_renamed.head()

,Country or region,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Score,Perceptions of corruption,Year
0,Finland,10.639267,0.954330,71.900825,0.949172,-0.059482,7.8087,0.195445,2020
1,Denmark,10.774001,0.955991,72.402504,0.951444,0.066202,7.6456,0.168489,2020
2,Switzerland,10.979933,0.942847,74.102448,0.921337,0.105911,7.5599,0.303728,2020
3,Iceland,10.772559,0.974670,73.000000,0.948892,0.246944,7.5045,0.711710,2020
4,Norway,11.087804,0.952487,73.200783,0.955750,0.134533,7.4880,0.263218,2020

In [16]:
#Check last 5 values of the data 
df_2018.tail()

,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Year
151,Yemen,3.355,0.442,1.073,0.343,0.244,0.083,0.064,2018
152,Tanzania,3.303,0.455,0.991,0.381,0.481,0.270,0.097,2018
153,South Sudan,3.254,0.337,0.608,0.177,0.112,0.224,0.106,2018
154,Central African Republic,3.083,0.024,0.000,0.010,0.305,0.218,0.038,2018
155,Burundi,2.905,0.091,0.627,0.145,0.065,0.149,0.076,2018

In [17]:
#Check last 5 values of the data 
df_2019.tail()

,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Year
151,Rwanda,3.334,0.359,0.711,0.614,0.555,0.217,0.411,2019
152,Tanzania,3.231,0.476,0.885,0.499,0.417,0.276,0.147,2019
153,Afghanistan,3.203,0.350,0.517,0.361,0.000,0.158,0.025,2019
154,Central African Republic,3.083,0.026,0.000,0.105,0.225,0.235,0.035,2019
155,South Sudan,2.853,0.306,0.575,0.295,0.010,0.202,0.091,2019

In [18]:
#Check last 5 values of the data 
df_2020_renamed.tail()

,Country or region,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Score,Perceptions of corruption,Year
148,Central African Republic,6.625160,0.319460,45.200001,0.640881,0.082410,3.4759,0.891807,2020
149,Rwanda,7.600104,0.540835,61.098846,0.900589,0.055484,3.3123,0.183541,2020
150,Zimbabwe,7.865712,0.763093,55.617260,0.711458,-0.072064,3.2992,0.810237,2020
151,South Sudan,7.425360,0.553707,51.000000,0.451314,0.016519,2.8166,0.763417,2020
152,Afghanistan,7.462861,0.470367,52.590000,0.396573,-0.096429,2.5669,0.933687,2020

## Check last 5 values of the data 
df_2021_renamed.tail()

In [19]:
combined_countries = pd.concat([df_2018,df_2019,df_2020_renamed,df_2021_renamed])
combined_countries.tail(149)

,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Year
0,Finland,7.842,10.775,0.954,72.000,0.949,-0.098,0.186,2021
1,Denmark,7.620,10.933,0.954,72.700,0.946,0.030,0.179,2021
2,Switzerland,7.571,11.117,0.942,74.400,0.919,0.025,0.292,2021
3,Iceland,7.554,10.878,0.983,73.000,0.955,0.160,0.673,2021
4,Netherlands,7.464,10.932,0.942,72.400,0.913,0.175,0.338,2021
...,...,...,...,...,...,...,...,...,...
144,Lesotho,3.512,7.926,0.787,48.700,0.715,-0.131,0.915,2021
145,Botswana,3.467,9.782,0.784,59.269,0.824,-0.246,0.801,2021
146,Rwanda,3.415,7.676,0.552,61.400,0.897,0.061,0.167,2021
147,Zimbabwe,3.145,7.943,0.750,56.201,0.677,-0.047,0.821,2021
148,Afghanistan,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,2021

In [20]:
combined_countries_without_year = combined_countries[['Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption']]

In [21]:
combined_countries_without_year.describe()

,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
count,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000,613.000000
mean,5.446171,5.061744,1.014611,32.166803,0.602518,0.085650,0.416267
std,1.104113,4.324451,0.304179,32.412930,0.228141,0.160419,0.340490
min,2.523000,0.000000,0.000000,0.000000,0.000000,-0.300907,0.000000
25%,4.628750,0.951500,0.810250,0.691500,0.440750,-0.033916,0.082000
50%,5.461100,1.574000,0.922247,1.048500,0.608415,0.098047,0.306000
75%,6.198750,9.482750,1.268750,66.303859,0.797174,0.191000,0.780623
max,7.842000,11.647000,1.644000,76.953000,0.974998,0.598000,0.939000

In [23]:
combined_countries.to_csv('Happinessavg.csv',index=False)